# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
---
services:
  sdlon:
    build: .
    command: ["uvicorn", "--factory", "sdlon.app:create_app", "--host", "0.0.0.0", "--reload"]
    environment:
      # OS2mo
      FASTRAMQPI__MO_URL: "http://mo:5000"
      FASTRAMQPI__CLIENT_ID: "dipex"
      FASTRAMQPI__CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
      FASTRAMQPI__AUTH_SERVER: "http://keycloak:8080/auth"
      FASTRAMQPI__AUTH_REALM: "mo"
      FASTRAMQPI__AMQP__URL: "amqp://guest:guest@msg-broker:5672/"
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./sdlon
        target: /app/sdlon

networks:
  default:
    external: true
    name: os2mo_default
