# Generated by ariadne-codegen on 2024-09-12 16:54
# Source: queries.graphql

from datetime import datetime
from typing import Any, List, Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class GetEngagements(BaseModel):
    engagements: "GetEngagementsEngagements"


class GetEngagementsEngagements(BaseModel):
    objects: List["GetEngagementsEngagementsObjects"]


class GetEngagementsEngagementsObjects(BaseModel):
    validities: List["GetEngagementsEngagementsObjectsValidities"]
    uuid: UUID


class GetEngagementsEngagementsObjectsValidities(BaseModel):
    person: List["GetEngagementsEngagementsObjectsValiditiesPerson"]
    org_unit: List["GetEngagementsEngagementsObjectsValiditiesOrgUnit"]
    validity: "GetEngagementsEngagementsObjectsValiditiesValidity"
    user_key: str
    job_function: "GetEngagementsEngagementsObjectsValiditiesJobFunction"
    engagement_type: "GetEngagementsEngagementsObjectsValiditiesEngagementType"


class GetEngagementsEngagementsObjectsValiditiesPerson(BaseModel):
    cpr_number: Optional[Any]
    uuid: UUID


class GetEngagementsEngagementsObjectsValiditiesOrgUnit(BaseModel):
    uuid: UUID
    user_key: str
    name: str


class GetEngagementsEngagementsObjectsValiditiesValidity(BaseModel):
    from_: datetime = Field(alias="from")
    to: Optional[datetime]


class GetEngagementsEngagementsObjectsValiditiesJobFunction(BaseModel):
    user_key: str
    name: str
    uuid: UUID


class GetEngagementsEngagementsObjectsValiditiesEngagementType(BaseModel):
    name: str
    user_key: str
    uuid: UUID


GetEngagements.update_forward_refs()
GetEngagementsEngagements.update_forward_refs()
GetEngagementsEngagementsObjects.update_forward_refs()
GetEngagementsEngagementsObjectsValidities.update_forward_refs()
GetEngagementsEngagementsObjectsValiditiesPerson.update_forward_refs()
GetEngagementsEngagementsObjectsValiditiesOrgUnit.update_forward_refs()
GetEngagementsEngagementsObjectsValiditiesValidity.update_forward_refs()
GetEngagementsEngagementsObjectsValiditiesJobFunction.update_forward_refs()
GetEngagementsEngagementsObjectsValiditiesEngagementType.update_forward_refs()
